version: '3.8'

services:
  frontend:
    image: mariana7/todolist-frontend:latest  # Use o nome da imagem no Docker Hub
    container_name: frontend
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: always
