version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000" 
    restart: always 
