version = 0.1
[default.deploy.parameters]
stack_name = "cognito-react"
resolve_s3 = true
s3_prefix = "cognito-react"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"dev\" S3BucketName=\"todolist-static-site\" CognitoUserPoolName=\"todolist-userpool\" CognitoWebClientName=\"todolist-webclient\""
image_repositories = []
