version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todolist
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todolist  # Alinha com o nome da base de dados que o backend vai usar
      MYSQL_USER: mariana
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "mariana", "--password=1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend_network  # Usa a mesma rede para ambos os serviços

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_USER: mariana  
      DB_PASSWORD: 1234  
      DB_HOST: mysql-todolist  
      DB_NAME: todolist  
      DB_PORT: 3306
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend_network  

networks:
  backend_network:
    driver: bridge
