version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_USER: admin
      DB_PASSWORD: adminpassword
      DB_HOST: shdjsakhjsd
      DB_NAME: todolist
      DB_PORT: 3306
      COGNITO_APP_CLIENT_ID: scjkds
      COGNITO_USERPOOL_ID: ahsjkdsahj
      COGNITO_DOMAIN: jxscndkc
      REDIRECT_URI: ashdasdjkasd
      COGNITO_APP_CLIENT_SECRET: hhshsjakssjkd
      AWS_REGION: eu-north-1
    ports:
      - "8000:8000"